steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - Dockerfile.web
      - --build-arg
      - VITE_API_BASE_URL=${_VITE_API_BASE_URL}
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/$PROJECT_ID/policing-apps/police-cases-kb:latest
  _VITE_API_BASE_URL: ""
options:
  logging: CLOUD_LOGGING_ONLY
